### ISSUE TITLE
Led3579

### ISSUE THREAD

**Issue by sergeyvasilievich** [ildarmustafin/esp8266_aquarium#1]
Привет дорогой Ильдар. А подскажи что показывают led3, led5, led7 и led9 ? Ну и если не сложно то про светодиоды AP и STA ?

**Comment by ildarmustafin** [comment]
Led 3, 5, 7, 9 не завязаны ни на что. Они на перспективу. Led AP загорается при  AP режиме. LED STA загорается при подключении к роутеру или другой точке доступа

**Comment by sergeyvasilievich** [comment]
Спасибо за ответ. Получается что pca9685 используется в проекте практически в холостую? Хотя стоит не дёшево. Смысл такого нагромождения если все ноги esp-шки свободны?

**Comment by ildarmustafin** [comment]
Изначально проект был без него. Первые платы также были без него. Ног не хватило на индикацию светодиодами. Тем более pca9685 имеет шим, который тупит на esp8266. Поэтому перешёл на него

**Comment by ildarmustafin** [comment]
Мне нужны пины для вентилятора, тэна светодиода(шим), реле1, реле2, кнопка1, кнопка2, ds18b20, Итого 8 пинов заняты

**Comment by sergeyvasilievich** [comment]
Да я знаю что проект был без него. Я даже хотел повторить его и вытравил плату и начал собирать, но что то перебило и я его забросил. Теперь все таки решив доделать, придется переделывать плату. А что у вас на реле1 и реле2 находится? И что за кнопка2?

**Comment by ildarmustafin** [comment]
Реле1 и реле2 - это реле времени, аналогичный светодиодному, только без шим. Кнопка1 - это вкл подсветки на lcd, кнопка2 - показать ip и port, кнопка3 - отладочная, показывает текущий и минимальный heap, а также общее количество перезагрузок контроллера. К сожалению у меня платы все разошлись, я бы отправил вам. На форуме выложена печатная плата, можно заказать   в китае. В январе выходило около 1200 руб за 5 плат

**Comment by sergeyvasilievich** [comment]
Спасибо Вам за ответы Ильдар. Заказал в Китае плату с pca9685,жду. Потом под неё разведу печатку и буду собирать. Если что будет непонятно напишу. Удачи в развитии проекта.
