### ISSUE TITLE
Переменные fileName & fileSize в цикле в модуле FS.ino

### ISSUE THREAD

**Issue by NguenChong** [ildarmustafin/esp8266_aquarium#1]
А зачем обход файловой системы в модуле FS.ino ?
```
while (dir.next()) {
    String fileName = dir.fileName();
    size_t fileSize = dir.fileSize();
}
```
Если это потом нигде не используется.

**Comment by ildarmustafin** [comment]
Все взято из примера FSBrowser, я лишь убрал вывод информации в порт. Полагаю, что она нужна только для вывода доп инфы в сериал порт. Но без нее веб страницу открывает через раз. поэтому я оставил ее
