### ISSUE TITLE
error 192.168.4.1: FileNotFound 

### ISSUE THREAD

**Issue by thodan36a** [ildarmustafin/esp8266_aquarium#1]
I was connected to Aqua wifi, but when I accessed 192.168.4.1, I received the following information: FileNotFound, Am I missing something?

**Comment by ildarmustafin** [comment]
Hi. you should upload file system

**Comment by ildarmustafin** [comment]
[ESP8266FS.zip](https://github.com/ildarmustafin/esp8266_aquarium/files/4182275/ESP8266FS.zip)
Extract this file to C:\Program Files (x86)\Arduino\tools. And restart arduino ide

**Comment by thodan36a** [comment]
Thank you, I uploaded the file successfully and there are some problems, thanks for helping me fix it:
- My date and time are not displayed correctly, I have adjusted the time zone and updated automatically, monitoring the arduino serial will result in a successful update.  I think it's a display issue, because it's not the same as the date and time format compiled yet).
- The graph shows the temperature does not represent correctly, my current temperature is 28oC but the graph does not exceed 24.
- In the timeline settings, there are words that I think are abbreviations or google that do not translate correctly, I do not understand what it is like?
- And finally, if there is a proposal for later versions, do you think that an automatic feeding schedule is needed?  Next, you can send data via mqtt to update information about temperature, lights ... Go to smart home like openhab or Hassio?
![Screenshot_20200211_011411](https://user-images.githubusercontent.com/22538216/74178963-107e1280-4c6f-11ea-9cf9-06aac3afbbc5.jpg)
![Screenshot_20200211_011513](https://user-images.githubusercontent.com/22538216/74178969-14aa3000-4c6f-11ea-82f1-37af15e7dcd6.jpg)
![Screenshot_20200211_011549](https://user-images.githubusercontent.com/22538216/74178983-1a077a80-4c6f-11ea-9b23-9607f4d7df7c.jpg)

**Comment by ildarmustafin** [comment]
Temperature of the graphic you can see in http://192.168.31.203/configChart.json. Update of the new average temperature point will be at 21:00 everyday. All procedure you can find on measure_t() function. As you can see it take 4 temperature measurement: at 3:00, 9:00, 15:00 and 21:00. After it make average value and send to the graphic

**Comment by ildarmustafin** [comment]
![mini_page_2](https://user-images.githubusercontent.com/7300933/74182034-1cb0a280-4c64-11ea-8804-339707f4cb05.jpg)

**Comment by ildarmustafin** [comment]
what kind ok clock do you use?ds3231?

**Comment by ildarmustafin** [comment]
I try mqtt and dislike it. Because mqtt need mqtt broker (server). So I make data(json datas) transmitting by websocket.

**Comment by thodan36a** [comment]
> what kind of clock do you use?ds3231? I think line is broken or battery discharged. You mustn't receive date like 165.165... because in file functions.js line 299 we have a function that check connection. And if there is no connection (165.165.165...) we will have message "RTC break"

I have also thought of this but in Redme and include_define.h I do not see a connection pin declaration for it?

**Comment by ildarmustafin** [comment]
ds3231 working by i2c. D1 - SCL, D2 - SDA

**Comment by thodan36a** [comment]
> ds3231 working by i2c. D1 - SCL, D2 - SDA

Oh, I didn't know it could be used with 2 PIN lcd16x02 (I'm using it for lcd as declaration), Many thanks for your great support, hope you will have new versions that integrate more features for the aquarium, good luck to you!

**Comment by ildarmustafin** [comment]
you r welcome. It will have the same pins, but different address. You can find your addresses with this sketch
[i2c_scanner.zip](https://github.com/ildarmustafin/esp8266_aquarium/files/4184509/i2c_scanner.zip)
