### ISSUE TITLE
Aquarium controller

### ISSUE THREAD

**Issue by digits1** [ildarmustafin/esp8266_aquarium#2]
Ильдар добрый вечер! Очень заинтересовала конструкция вашего аквариумного контроллера. У меня вопрос такого характера, есть ли у вас исходники или бинарник на большее количество (дискретных) релейных выходов? Хотябы ещё парочку. Если есть возможность поделитесь пожалуйста. Моя почта: digits1@yandex.ru. Спасибо, с уважением.

**Comment by ildarmustafin** [comment]
Приветствую. Выход идёт через 16-канальный шим PCA9685, которые могут использоваться и как дискрет. Исходников на большее количество нет. Могу выслать исходники существующего проекта, поправите сами сколько нужно будет. Только я не знаю как вы будете реализовывать это в веб интерфейсе
