### ISSUE TITLE
Can you add temperature calibration to the next versions?

### ISSUE THREAD

**Issue by thodan36a** [ildarmustafin/esp8266_aquarium#4]
Hi, this is a great project, I have tried it and the one problem is that the sensor is usually inaccurate. The ds18b20 alone is 1°C smaller than the DHT22 and the mercury thermometer. Can you add temperature calibration to the next versions?

**Comment by ildarmustafin** [comment]
Hi. Project already has temperature correction in third tab 1 row

**Comment by thodan36a** [comment]
> Hi. Project already has temperature correction in third tab 1 row

Sorry i don't think this is the place to ask about this but i don't know how to talk to you. Can you share pcb file, I don't have electronics expertise so i can't convert schematic file to pcb to order. :)
thanks!

**Comment by ildarmustafin** [comment]
ildarmustafin@yahoo.com
