### ISSUE TITLE
Error Compiling FS:197:21: error: variable or field 'handleDoUpdate' declared void

### ISSUE THREAD

**Issue by liwajaya** [ildarmustafin/esp8266_aquarium#5]
Please enlighten me, I compiled with Arduino IDE 1.8 to get an error like this

`WARNING: library LiquidCrystal_I2C claims to run on avr architecture(s) and may be incompatible with your current board which runs on esp8266 architecture(s).
FS:197:21: error: variable or field 'handleDoUpdate' declared void

 void handleDoUpdate(AsyncWebServerRequest *request, const String& filename, size_t index, uint8_t *data, size_t len, bool final) {

                     ^

FS:197:21: error: 'AsyncWebServerRequest' was not declared in this scope

FS:197:44: error: 'request' was not declared in this scope

 void handleDoUpdate(AsyncWebServerRequest *request, const String& filename, size_t index, uint8_t *data, size_t len, bool final) {

                                            ^

FS:197:53: error: expected primary-expression before 'const'

 void handleDoUpdate(AsyncWebServerRequest *request, const String& filename, size_t index, uint8_t *data, size_t len, bool final) {

                                                     ^

FS:197:84: error: expected primary-expression before 'index'

 void handleDoUpdate(AsyncWebServerRequest *request, const String& filename, size_t index, uint8_t *data, size_t len, bool final) {

                                                                                    ^

FS:197:99: error: expected primary-expression before '*' token

 void handleDoUpdate(AsyncWebServerRequest *request, const String& filename, size_t index, uint8_t *data, size_t len, bool final) {

                                                                                                   ^

FS:197:100: error: 'data' was not declared in this scope

 void handleDoUpdate(AsyncWebServerRequest *request, const String& filename, size_t index, uint8_t *data, size_t len, bool final) {

                                                                                                    ^

FS:197:113: error: expected primary-expression before 'len'

 void handleDoUpdate(AsyncWebServerRequest *request, const String& filename, size_t index, uint8_t *data, size_t len, bool final) {

                                                                                                                 ^

In file included from C:\Users\liwajaya1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/Arduino.h:29:0,

                 from sketch\main.ino.cpp:1:

FS:197:118: error: expected primary-expression before 'bool'

 void handleDoUpdate(AsyncWebServerRequest *request, const String& filename, size_t index, uint8_t *data, size_t len, bool final) {

                                                                                                                      ^

MQTT:15:23: error: variable or field 'onMqttDisconnect' declared void

 void onMqttDisconnect(AsyncMqttClientDisconnectReason reason) {

                       ^

MQTT:15:23: error: 'AsyncMqttClientDisconnectReason' was not declared in this scope

WIFI:13:16: error: variable or field 'WiFiEvent' declared void

 void WiFiEvent(WiFiEvent_t event) {

                ^

WIFI:13:16: error: 'WiFiEvent_t' was not declared in this scope

websocket:11:16: error: variable or field 'onWsEvent' declared void

 void onWsEvent(AsyncWebSocket * server, AsyncWebSocketClient * client, AwsEventType type, void * arg, uint8_t *data, size_t len) {

                ^

websocket:11:16: error: 'AsyncWebSocket' was not declared in this scope

websocket:11:33: error: 'server' was not declared in this scope

 void onWsEvent(AsyncWebSocket * server, AsyncWebSocketClient * client, AwsEventType type, void * arg, uint8_t *data, size_t len) {

                                 ^

websocket:11:41: error: 'AsyncWebSocketClient' was not declared in this scope

 void onWsEvent(AsyncWebSocket * server, AsyncWebSocketClient * client, AwsEventType type, void * arg, uint8_t *data, size_t len) {

                                         ^

websocket:11:64: error: 'client' was not declared in this scope

 void onWsEvent(AsyncWebSocket * server, AsyncWebSocketClient * client, AwsEventType type, void * arg, uint8_t *data, size_t len) {

                                                                ^

websocket:11:72: error: 'AwsEventType' was not declared in this scope

 void onWsEvent(AsyncWebSocket * server, AsyncWebSocketClient * client, AwsEventType type, void * arg, uint8_t *data, size_t len) {

                                                                        ^

websocket:11:91: error: expected primary-expression before 'void'

 void onWsEvent(AsyncWebSocket * server, AsyncWebSocketClient * client, AwsEventType type, void * arg, uint8_t *data, size_t len) {

                                                                                           ^

websocket:11:111: error: expected primary-expression before '*' token

 void onWsEvent(AsyncWebSocket * server, AsyncWebSocketClient * client, AwsEventType type, void * arg, uint8_t *data, size_t len) {

                                                                                                               ^

websocket:11:112: error: 'data' was not declared in this scope

 void onWsEvent(AsyncWebSocket * server, AsyncWebSocketClient * client, AwsEventType type, void * arg, uint8_t *data, size_t len) {

                                                                                                                ^

websocket:11:125: error: expected primary-expression before 'len'

 void onWsEvent(AsyncWebSocket * server, AsyncWebSocketClient * client, AwsEventType type, void * arg, uint8_t *data, size_t len) {

                                                                                                                             ^

C:\Users\LIWAJA~1\AppData\Local\Temp\arduino_modified_sketch_99263\main.ino: In function 'String jsonReadToStr(String&, String)':

main:2:3: error: 'DynamicJsonBuffer' was not declared in this scope

   DynamicJsonBuffer jsonBuffer;

   ^

main:2:21: error: expected ';' before 'jsonBuffer'

   DynamicJsonBuffer jsonBuffer;

                     ^

main:3:3: error: 'JsonObject' was not declared in this scope

   JsonObject& root = jsonBuffer.parseObject(json);

   ^

main:3:15: error: 'root' was not declared in this scope

   JsonObject& root = jsonBuffer.parseObject(json);

               ^

main:3:22: error: 'jsonBuffer' was not declared in this scope

   JsonObject& root = jsonBuffer.parseObject(json);

                      ^

main:4:30: error: expected primary-expression before '>' token

   return root[name].as<String>();

                              ^

main:4:32: error: expected primary-expression before ')' token

   return root[name].as<String>();

                                ^
`

**Comment by ildarmustafin** [comment]
Sorry for late answer. I use latest arduino ide 1.8.13 and esp 2.7.3. Have you install Async libraries?
